services:
  coordination:
    build:
      context: .
      target: coordination

    environment:
      - TS_CLIENT_ID=${TS_CLIENT_ID}
      - TS_CLIENT_SECRET=${TS_CLIENT_SECRET}
      - TS_HOSTNAME=tailsys-coordination-test
      - DEV_MODE=true
    command:
      - co
      
  client:
    build:
      context: .
      target: client
    environment:
      - TS_CLIENT_ID=${TS_CLIENT_ID}
      - TS_CLIENT_SECRET=${TS_CLIENT_SECRET}
      - TS_HOSTNAME=tailsys-client-test
      - COORDINATION_SERVER=tailsys-coordination-test:6655
    command:
      - c

  # command-test:
  #   build:
  #     context: .
  #     target: ni 
  #   environment:
  #     TS_CLIENT_ID: ${TS_CLIENT_ID}
  #     TS_CLIENT_SECRET: ${TS_CLIENT_SECRET}
  #     TS_HOSTNAME: "tailsys-ni-test"
