// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: command.proto

package commands

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CommandRunner_Command_FullMethodName = "/tailsys.CommandRunner/Command"
)

// CommandRunnerClient is the client API for CommandRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandRunnerClient interface {
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResonse, error)
}

type commandRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandRunnerClient(cc grpc.ClientConnInterface) CommandRunnerClient {
	return &commandRunnerClient{cc}
}

func (c *commandRunnerClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResonse, error) {
	out := new(CommandResonse)
	err := c.cc.Invoke(ctx, CommandRunner_Command_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandRunnerServer is the server API for CommandRunner service.
// All implementations must embed UnimplementedCommandRunnerServer
// for forward compatibility
type CommandRunnerServer interface {
	Command(context.Context, *CommandRequest) (*CommandResonse, error)
	mustEmbedUnimplementedCommandRunnerServer()
}

// UnimplementedCommandRunnerServer must be embedded to have forward compatible implementations.
type UnimplementedCommandRunnerServer struct {
}

func (UnimplementedCommandRunnerServer) Command(context.Context, *CommandRequest) (*CommandResonse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Command not implemented")
}
func (UnimplementedCommandRunnerServer) mustEmbedUnimplementedCommandRunnerServer() {}

// UnsafeCommandRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandRunnerServer will
// result in compilation errors.
type UnsafeCommandRunnerServer interface {
	mustEmbedUnimplementedCommandRunnerServer()
}

func RegisterCommandRunnerServer(s grpc.ServiceRegistrar, srv CommandRunnerServer) {
	s.RegisterService(&CommandRunner_ServiceDesc, srv)
}

func _CommandRunner_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandRunnerServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandRunner_Command_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandRunnerServer).Command(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandRunner_ServiceDesc is the grpc.ServiceDesc for CommandRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tailsys.CommandRunner",
	HandlerType: (*CommandRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _CommandRunner_Command_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command.proto",
}
